### ISSUE TITLE
Affix Info for Dictionary

### ISSUE THREAD

**Issue by Everspace** [SynthSy/PSO2-Dictionary#2]
Affix Names:

## Stat Special

|Fan Translation Name| NA Name|
|:-|:-|
| Modulator | Modulator |
| Alter Arma | Alter Arma |
| Flict Arma | Flict Arma |

## Monster Soul

|Fan Translation Name| NA Name|
|:-|:-|
| Signo Soul | Signo Soul
| Snow Soul | Snow Soul |
| Persona Soul | Persona Soul |

## Special

|Fan Translation Name| NA Name|
|:-|:-|
| Another History | Alternate History |

**Comment by SynthSy** [comment]
Thank you.
