### ISSUE TITLE
Fresh Finds item wrong price

### ISSUE THREAD

**Issue by 3Nya3** [SynthSy/PSO2-Dictionary#3]
The Starry sky stole is 160 sg on the NA fresh finds shop
![image](https://user-images.githubusercontent.com/43357430/86841276-bcd2f200-c071-11ea-9f93-b27662ff1f42.png)

**Comment by Aida-Enna** [comment]
It occurs to me that issues would be sent to Synth, not me. Whoops! I'll go ahead and fix this though, thank you!
